name: cloud-payment-platform

services:
  postgres:
    image: postgres:14
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .postgres_env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud-payment-platform-edge
      - cloud-payment-platform-backend

volumes:
  postgres_data:

networks:
  cloud-payment-platform-edge:
    driver: bridge

  cloud-payment-platform-backend:
    driver: bridge
    internal: true