spring:
  datasource:
    url: jdbc:${POSTGRES_URL}/cloud-payment-platform
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

feign:
  order:
    url: http://order-service:8081/v1/orders

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

app:
  outbox:
    fixed-delay: 2000
    page-size: 512
    default-sort-column: creationTimestamp

info:
  app:
    name: payment-service
    description: Payment processing platform
    version: 1.0.0