server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-payment-platform
    username: ${POSTGRES_USER:cloud-payment-platform}
    password: ${POSTGRES_PASSWORD:changeIt}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: paymentservice
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    default_schema: paymentservice

feign:
  order:
    url: http://localhost:8081
  client:
    connectTimeout: 5000
    readTimeout: 5000
    loggerLevel: full

app:
  kafka:
    payment-topic: payments.payment.completed

  outbox:
    fixed-delay: 2000
    page-size: 512
    default-sort-column: creationTimestamp

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"