server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: super-secret-which-no-one-should-ever-know

app:
  token:
    expiration: 60000
    secret: super-secret-which-no-one-should-ever-know

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics, gateway"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true
    gateway:
      enabled: true
      access: read-only
