spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payments
              uri: http://payment-service:8082
              predicates:
                - Path=/v1/payments,/v1/payments/**
                - Method=POST

            - id: orders
              uri: http://order-service:8081
              predicates:
                - Path=/v1/orders,/v1/orders/**
                - Method=POST

logging:
  level:
    org.springframework.cloud.gateway: TRACE