server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics, gateway"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true
    gateway:
      enabled: true
      access: read-only
