server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-payment-platform
    username: ${POSTGRES_USER:cloud-payment-platform}
    password: ${POSTGRES_PASSWORD:changeIt}
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: notificationservice
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    default_schema: notificationservice

app:
  kafka:
    payment-topic: payments.payment.completed

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"
