spring:
  datasource:
    url: jdbc:${POSTGRES_URL}/cloud-payment-platform
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true

info:
  app:
    name: notification-service
    description: Notification processing platform
    version: 1.0.0